import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Inter, Calistoga} from 'next/font/google';


const inter = Inter({ subsets:['latin'], variable: '--font-sans'});
const calistoga = Calistoga({ subsets:['latin'], variable: '--font-serif', weight:["400"]});
import next from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-gray-900 text-white antialiased"
      >
        {children}
      </body>
    </html>
  );
}
